server:
  port: 8081
spring:
    application:
        name: omnitask
    datasource:
        url: jdbc:postgresql://localhost:5432/omnitask
        username: postgres
        password: admin123
        driver-class-name: org.postgresql.Driver